[package]
name = "hybrid_nars_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
nom = "8.0.0"
rand = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-big-array = "0.5"
